stages:
  - setup
  - unit-test
  - build
  - release
  - deploy
variables:
  IMAGE: siscc/dotstatsuite-webapp-template
  CONTAINER_IMAGE: $IMAGE:$CI_COMMIT_SHORT_SHA
  LATEST_CONTAINER_IMAGE: $IMAGE:latest
  TAG_CONTAINER_IMAGE: $IMAGE:$CI_COMMIT_REF_NAME
  CI_REGISTRY: https://index.docker.io/v1/
  CI_REGISTRY_AUTH: ZWJhc2xleTpmcmVlcmlkZTE0
setup:
  stage: setup
  image: node:alpine
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/
  tags:
    - kube
    - oecd
unit test:
  stage: unit-test
  image: node:alpine
  script:
    - yarn test
  dependencies:
    - setup
  tags:
    - docker
build:
  stage: build
  image: node:alpine
  artifacts:
    paths:
      - dist/
  script:
    - yarn dist
  tags:
    - kube
    - oecd
build and push docker image:
  stage: release
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$CI_REGISTRY_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CONTAINER_IMAGE --destination $LATEST_CONTAINER_IMAGE --destination $TAG_CONTAINER_IMAGE
  dependencies:
    - setup
    - build
  only:
    - develop
    - master
  tags:
    - kube
    - oecd
deploy staging:
  stage: deploy
  image: google/cloud-sdk
  before_script:
    - echo ${KUBE_ACCOUNT_KEY} | base64 -di > key.json
  script:
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project oecd-228113
    - gcloud config set container/cluster oecd
    - gcloud config set compute/region europe-west1-b
    - gcloud container clusters get-credentials oecd --region europe-west1-b
    - kubectl get pods -n staging -o wide
    - kubectl set image deployment/webapp webapp=$CONTAINER_IMAGE -n staging
    - kubectl set env deployment/webapp GIT_HASH=$CI_COMMIT_SHA -n staging
  only:
    - develop
  environment:
    name: staging
  tags:
    - kube
    - oecd
